### ISSUE TITLE
redirect_uri_mismatch when trying to log in with Google

### ISSUE THREAD

**Issue by Eschon** [LoopTeam/LoopSeries-Website#31]
When I try to log in with Google I get an redirect_uri_mismatch error.

**Comment by joshlopes** [comment]
Hi @Eschon , does this happen in a fork or on our official website "www.loop-anime.com" ?

**Comment by Eschon** [comment]
Thanks on "www.loop-anime.com" it works I was using the link on the top of the repository which is "www.loop-series.com". If this link is wrong you should probably change it.

**Comment by joshlopes** [comment]
yeah, for now it is loop-anime. There is still things to assert! Thanks.
